name: blood_donor
description: "An app to help volunteers find blood donors in their area."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_spinkit: ^5.2.1
  geolocator: ^14.0.1
  get: ^4.7.2
  get_storage: ^2.1.1
  google_maps_flutter: ^2.12.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  path: ^1.9.1
  pdf: ^3.11.3
  printing: ^5.14.2
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - .env
  - assets/icons/
